"""create facts and pool tables

Revision ID: 0a98a20fdb07
Revises: 
Create Date: 2026-04-23 22:28:30.701989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a98a20fdb07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_license', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), server_default='en', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('era', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_date'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_facts_source_external')
    )
    op.create_index('idx_facts_scheduled_date', 'facts', ['scheduled_date'], unique=False)
    op.create_table('pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_license', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), server_default='en', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('era', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending_review', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'approved', 'rejected')", name='ck_pool_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_pool_source_external')
    )
    op.create_index('idx_pool_status', 'pool', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pool_status', table_name='pool')
    op.drop_table('pool')
    op.drop_index('idx_facts_scheduled_date', table_name='facts')
    op.drop_table('facts')
    # ### end Alembic commands ###
